apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
  labels:
    app: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: <your image>
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "512Mi"
        command:
        - /entrypoint.sh
        - scheduler
        env:
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: db_uri
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: db_uri
        - name: AIRFLOW__CELERY__BROKER_URL
          value: redis://airflow-redis:6379/1
        - name: AIRFLOW__CORE__LOGGING_LEVEL
          value: DEBUG
        - name: FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: fernet_key
        - name: EXECUTOR
          value: "Celery"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        - name: AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS
          value: "False"
